### ISSUE TITLE
The tax calculation code for EPF is inaccurate, and some fields are not user-friendly. This causes errors in tax calculations and makes the user experience difficult.

### ISSUE THREAD

**Issue by AayushBdrShahi** [Sulokp/TaxCalculator#10]
: Inaccurate EPF Tax Calculation Description: EPF tax calculation logic is incorrect, resulting in inaccurate tax amounts. Steps to Reproduce:

**Comment by Sulokp** [comment]
I have corrected the overall logic accordingly. Please let me know if any other issue are up.
